apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  application-dev.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}
        username: {{ .Values.postgres.username }}
        password: {{ .Values.postgres.password }}
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          idle-timeout: 300000
          max-lifetime: 1800000
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
      cloud:
        openfeign:
          client:
            config:
              product-inventory-controller:
                url: http://product-catalog-ms.absolutehealth.svc.cluster.local:80/catalog/inventory
    server:
      port: {{ .Values.app.port }}
    springdoc:
      api-docs:
        path: /v3/shoppingcart-docs
    
